### ISSUE TITLE
leviathan.py won't run

### ISSUE THREAD

**Issue by gotsathacker1** [lnjustify/leviathan-framework#1]
Not particularly sure why but I followed the setup steps and when I try to use python3 leviathan.py it gives me a print statement error:
 
        /usr/local/lib/python3.10/dist-packages/leviathan# python3 leviathan.py
           File "/usr/local/lib/python3.10/dist-packages/leviathan/leviathan.py", line 82
           print """
           ^^^^^^^^^
       SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by lulzbinbashspider** [comment]
Sorry bro , use ;
git clone https://github.com/leviathan-framework/leviathan.git
cd leviathan
pip3 install -r requirements.txt
python -m pip install -r requirements.txt
bash scripts/debian_install.shpython2.7 leviathan.py

Enviado con el correo electrónico seguro de [Proton Mail](https://proton.me/).

------- Original Message -------

**Comment by gotsathacker1** [comment]
Allgood everything was fine with what you gave me thank you, except for the last line which should've actually been: bash scripts/debian_install.sh python2.7 leviathan.py
I guess I wasn't paying attention though and it seems that everything is written in Python2.x(I'm guessing by the line you sent me 2.7) as I'm not using that I'll have to go through sometime in the future when I have spare time and fix that I guess because this means that all the print statements need to be changed and the raw_input made into input, if I want it to be compatible with 2.x and 3.x. Thank you for taking the time to help me though I appreciate it.
